In [9]:
import numpy as np

x = np.arange(4.0).reshape((2, 2))
y = np.zeros((2,2), dtype='float32')
print('x=',x)
print('y=',y)

x= [[0. 1.]
 [2. 3.]]
y= [[0. 0.]
 [0. 0.]]


In [10]:
z = np.add(x,y)
print(z)

[[0. 1.]
 [2. 3.]]


In [12]:
f1 = np.arange(5)
print(f1)

[0 1 2 3 4]


In [18]:
f2 = np.arange(10)
f3 = np.append(f1,f2)
print(f3)

[0 1 2 3 4 0 1 2 3 4 5 6 7 8 9]
